parameters:
#    memeoirs_users.example.class: Memeoirs\UsersBundle\Example

services:
#    memeoirs_users.example:
#        class: %memeoirs_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
