#Memeoirs\UsersBundle\Entity\User:
#    properties:
    # Your custom fields in your user entity, here is an example of fullName
        #fullName:
        #    - NotBlank:
        #        message: memeoirs_user.first_name.blank
        #        groups: [ "MemeoirsProfile" ]
        #    - Length:
        #        min: 2
        #        minMessage: memeoirs_user.first_name.short
        #        max: 255
        #        maxMessage: memeoirs_user.first_name.long
        #        groups: [ "MemeoirsProfile" ]



# Note: We still want to validate the email
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and email fields
#
# As you can see, we are only applying the UniqueEntity constraint to 
# the email field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
             fields: email
             errorPath: email 
             message: fos_user.email.already_used
             groups: [ "MemeoirsRegistration", "MemeoirsProfile" ]

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "MemeoirsRegistration", "MemeoirsProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "MemeoirsRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "MemeoirsRegistration", "MemeoirsProfile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "MemeoirsRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                minMessage: fos_user.password.blank
                groups: [ "MemeoirsRegistration", "MemeoirsProfile", "ResetPassword", "ChangePassword"]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "MemeoirsRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "MemeoirsRegistration" ]

FOS\UserBundle\Propel\User:
    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "MemeoirsRegistration", "MemeoirsProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "MemeoirsRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "MemeoirsRegistration", "MemeoirsProfile" ]

        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "MemeoirsRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                minMessage: fos_user.password.blank
                groups: [ "MemeoirsRegistration", "MemeoirsProfile", "ResetPassword", "ChangePassword"]


FOS\UserBundle\Propel\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "MemeoirsRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "MemeoirsRegistration" ]